### ISSUE TITLE
Running the tests makes the package dirty, preventing it from being updated or removed

### ISSUE THREAD

**Issue by tkelman** [brandonkmiller/ConfParser.jl#7]
You're modifying the file `test/confs/out.conf` when running the tests. This is bad since Julia packages are active git repositories, and a dirty state is assumed to be local work that the package manager won't overwrite by default. You should do something with a gitignore, maybe modify a separate file if you want that one as a reference or example.

**Comment by brandonkmiller** [comment]
@tkelman excellent point - I had not thought of that. Fixed this issue by rm'ng out.conf (if exists) at the end of runtests.jl (reference commit 25322bc72342707afde1b285fc74630b880bdfdd)

Thanks!
