### ISSUE TITLE
The Configuration file could not be opened

### ISSUE THREAD

**Issue by erdongwei** [brandonkmiller/ConfParser.jl#8]
I have installed the package, and when used it to open a .ini file, it says that the configuration file could not be opened.  The following is the code, anyone have an idea?

using ConfParser
push!(LOAD_PATH,pwd())
conf = ConfParse("voting.ini")
parse_conf!(conf)

**Comment by brandonkmiller** [comment]
@erdongwei could provide the content in the configuration file and the error output? Do you have proper permissions to open the file?

**Comment by brandonkmiller** [comment]
@erdongwei I'm going to close this issue because I don't think it's a ConfParser issue. If it's a config file format problem ConfParser will throw an error when trying to auto-identify the syntax. An error stating a file can't be opened usually eludes to a permissions problem.
